#Task2: Try Linear regression on same prediction data using Tensorflow

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [4]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.29437053, 0.00217875],
       [0.7269421 , 0.60247434],
       [0.58632185, 0.83586757]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([1.21637132, 0.33731545])>


In [5]:
def model(s):
    return s @ v + r

In [6]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[ 96.62238033  76.8044497 ]
 [129.49959282 107.04884706]
 [158.24351637 129.73874613]
 [ 84.19458411  57.39304386]
 [132.35690909 116.83591475]
 [ 96.62238033  76.8044497 ]
 [129.49959282 107.04884706]
 [158.24351637 129.73874613]
 [ 84.19458411  57.39304386]
 [132.35690909 116.83591475]
 [ 96.62238033  76.8044497 ]
 [129.49959282 107.04884706]
 [158.24351637 129.73874613]
 [ 84.19458411  57.39304386]
 [132.35690909 116.83591475]], shape=(15, 2), dtype=float64)


In [7]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(1078.6520634726608, shape=(), dtype=float64)


In [8]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 1078.6520634726608
 
 Epoch count: 1 
 Loss value: 716.4643066642382
 
 Epoch count: 2 
 Loss value: 484.86774231951046
 
 Epoch count: 3 
 Loss value: 335.5821205561712
 
 Epoch count: 4 
 Loss value: 238.3282668417174
 
 Epoch count: 5 
 Loss value: 174.0976363863606
 
 Epoch count: 6 
 Loss value: 130.9406423150974
 
 Epoch count: 7 
 Loss value: 101.33085746171534
 
 Epoch count: 8 
 Loss value: 80.51519820186738
 
 Epoch count: 9 
 Loss value: 65.48104157710225
 
 Epoch count: 10 
 Loss value: 54.309387184709344
 
 Epoch count: 11 
 Loss value: 45.76960939674545
 
 Epoch count: 12 
 Loss value: 39.06541970102223
 
 Epoch count: 13 
 Loss value: 33.67548881537291
 
 Epoch count: 14 
 Loss value: 29.253343136156698
 
 Epoch count: 15 
 Loss value: 25.564391717244593
 
 Epoch count: 16 
 Loss value: 22.446224725540855
 
 Epoch count: 17 
 Loss value: 19.783507958727846
 
 Epoch count: 18 
 Loss value: 17.492041518525305
 
 Epoch count: 19 
 Loss value: